### PR TITLE
double precision functions

### PR DESCRIPTION
**Pull request by chillenb**
I think I got the "identical_to_sleef" test to work with double precision functions. I'm really fumbling in the dark with all the templates, so definitely check the changes to the .tsv files for correctness. But hey, it builds and runs!

Also, I couldn't figure out how to make the macros in define_dispatchers.h do double duty, so I duplicated them; you probably don't want to keep those changes.

Let me know if you want to use any of this, and I'll clean up all the rest.

### CODE REVIEW

**Comment by bnprks** [comment]
Hi @chillenb, thanks for your interest in this! I'm curious what use case has brought you to this project, but happy to help spin it back up some to finish off the double-precision functionality.

It looks like I accidentally had some changes that never made it into the github repo, so I have now pushed those to the main branch, rebased on top of your py_tree_sitter version update. It looks like there was already a substantial amount of double-precision functionality that I had done. 

I'm afraid those probably will introduce lots of conflicts with your changes, and some of it is duplicated work of what you have just worked on -- so sorry about that. I don't have a ton of time to put back into this project at the moment, so I'll have to rely on you to rebase on to the updated main branch and figure out conflicts if you have further changes you want to add on top of the commits I just dug up.

My memory of where this project was before I took a break from it is the next steps were:
  - Implementation and benchmarking of most functions was good (maybe some stragglers for 2-argument functions)
  - I had just discovered that CPU instructions on subnormal floating point numbers run much slower, which necessitated a rethink of my benchmarking strategy
  - Needed complete testing for the special float functions (like remainder, modf, nextafter)
  - Update the master benchmarking table
  - Diagnose + fix any easy performance regressions from Highway in x86 (usually cases where a Highway function does more work than the sleef equivalent)

Overall, I think my conclusions from benchmarking is that the sleef functions will mainly be useful to expand the math functionality available in Highway, since the functions Highway has are usually equivalent and sometimes better than the sleef translations.

Again, sorry for not having had all my work up on github which has caused some duplicate work between us. I honestly was not expecting anyone to find and build on this project in the mean time. Happy to work with you on merging in any further changes on your docket though :)

**Comment by chillenb** [comment]
Thanks so much for pushing your updates! I don't mind the duplication of work -- that is just the nature of SIMD projects🤣. I trust what you wrote more than what I cobbled together, anyway.

It's a bit of a pipe dream, but I'd like to make something like [pnumpy](https://github.com/Quansight/pnumpy) which compiles on most architectures and provides multithreaded SIMD (1ULP) math functions, fast array arithmetic, etc. Numexpr and numba are nice, but they only use SVML/VML, and I wish they were more flexible.

Highway seems like a convenient way to write such a package, so it'd be really nice if your project gets upstreamed! I should have some time this summer to write some of the necessary tests and benchmarks, and will let you know when that happens.

**Comment by bnprks** [comment]
Interesting idea! For 1 ULP math functions I've assumed that LLVM had good vectorized implementations but looking at their [docs](https://llvm.org/docs/Vectorizers.html#vectorization-of-function-calls) I guess their function selection might be rather limited.

Yeah, keep in touch -- I'm busy for the immediate future as well but it would be cool to try finally getting this upstream over the summer :). Given that numpy core has started adding in some highway pull requests that's an eventually possible destination for some functions.

**Comment by chillenb** [comment]
It certainly would be cool if NumPy started using this! The NumPy developers did express some interest in Sleef, but they decided not to use it. I'm sure they would consider using the ported functions if they're available through Highway.

BTW, I tried making clang emit AVX2/AVX512 cosine, but absolutely could not get it to do more than 2 doubles at a time. [Link](https://godbolt.org/z/z5a8GYcPq). Have you had success with this in the past?

Edit: GCC has [libmvec](https://sourceware.org/glibc/wiki/libmvec), but it's only good to 4ULP... But it [does AVX512 cos](https://godbolt.org/z/31WPMnfnj)

**Comment by bnprks** [comment]
Ah, I guess llvm is really not as on top of things as I was expecting. To be fair, they probably have pretty stringent accuracy targets that might make vectorization harder than it is for sleef.

I also just took a look trying to get clang to emit vectorized cosine and it looks like it really doesn't want to ([link](https://godbolt.org/z/ee6jb1WW7) using zig, which provides direct access to the llvm vector types and is even emitting the "right" llvm instruction `%4 = call <4 x float> @llvm.cos.v4f32(<4 x float> %0)`)

**Pull request closed without merging**
